TestProjectWeb/Models/Quiz/CreateQuizViewModel.cs
using System.ComponentModel.DataAnnotations;
using TestProjectWeb.Data.Enums;

namespace TestProjectWeb.Models
{
    public class CreateQuizViewModel
    {
        public string Title { get; set; }
        public int QuestionsQuantity { get; set; }
    }
}

TestProjectWeb/Models/Quiz/QuestionViewModel.cs
using System.ComponentModel.DataAnnotations;
using TestProjectWeb.Data.Enums;

namespace TestProjectWeb.Models
{
    public class QuestionViewModel
    {
        public string Ask { get; set; }
        public string Answer { get; set; }

        public List<VariantViewModel> VariantViewModels { get; set; }
    }
}

TestProjectWeb/Models/Quiz/QuizViewModel.cs
using System.ComponentModel.DataAnnotations;
using TestProjectWeb.Data.Enums;

namespace TestProjectWeb.Models
{
    public class QuizViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }

        public List<QuestionViewModel> QuestionViewModels { get; set; }
    }
}

TestProjectWeb/Models/Quiz/VariantViewModel.cs
using System.ComponentModel.DataAnnotations;
using TestProjectWeb.Data.Enums;

namespace TestProjectWeb.Models
{
    public class VariantViewModel
    {
        public string Value { get; set; }
    }
}

TestProjectWeb/Controllers/QuizController.cs
using Microsoft.AspNetCore.Mvc;
using TestProjectWeb.Data;
using TestProjectWeb.Data.DbModels;
using TestProjectWeb.Models;
using TestProjectWeb.Services;

namespace TestProjectWeb.Controllers
{
    public class QuizController : Controller
    {
        private WordRepository _wordRepository;
        private UserService _userService;
        private QuizService _quizService;
        private QuizRepository _quizRepository;

        private const int MINQUESTIONSQUANTITY = 4;

        public QuizController(WordRepository wordRepository, UserService userService, QuizService quizService, QuizRepository quizRepository)
        {
            _wordRepository = wordRepository;
            _userService = userService;
            _quizService = quizService;
            _quizRepository = quizRepository;
        }

        public IActionResult MyQuizzes()
        {
            var user = _userService.GetCurrentUser();
            var myQuizzes = _quizRepository.GetByCreaterId(user.Id);
            var quizViewModels = new List<QuizViewModel>();
            foreach (var quiz in myQuizzes)
            {
                var quizViewModel = new QuizViewModel
                {
                    Id = quiz.Id,
                    Title = quiz.Title
                };
                quizViewModels.Add(quizViewModel);
            }
            return View(quizViewModels);
        }

        [HttpGet]
        public IActionResult CreateQuiz()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateQuiz(CreateQuizViewModel createQuizViewModel)
        {
            var user = _userService.GetCurrentUser();
            var maxUserWordsQuantity = _wordRepository.GetAllByCreaterId(user.Id).Count;
            if (maxUserWordsQuantity < MINQUESTIONSQUANTITY)
            {
                ModelState.AddModelError("QuestionsQuantity", $"Add {MINQUESTIONSQUANTITY - maxUserWordsQuantity} more words to your vocabulary to create quiz!");
            }
            if (maxUserWordsQuantity < createQuizViewModel.QuestionsQuantity)
            {
                ModelState.AddModelError("QuestionsQuantity", $"Max questions quantity is {maxUserWordsQuantity}!");
            }
            if (MINQUESTIONSQUANTITY > createQuizViewModel.QuestionsQuantity)
            {
                ModelState.AddModelError("QuestionsQuantity", $"Min questions quantity is {MINQUESTIONSQUANTITY}!");
            }
            if (!ModelState.IsValid)
            {
                return View();
            }
            var quiz = _quizService.CreateQuiz(createQuizViewModel.Title, createQuizViewModel.QuestionsQuantity);

            _quizRepository.Create(quiz);

            return RedirectToAction("myQuizzes");
        }

        public IActionResult PlayQuiz(int id)
        {
            var quiz = _quizRepository.GetById(id);

            var questionViewModels = new List<QuestionViewModel>();

            foreach (var question in quiz.Questions)
            {
                var variantViewModels = new List<VariantViewModel>();
                foreach (var variant in question.Variants)
                {
                    var variantViewModel = new VariantViewModel
                    {
                        Value = variant.Value,
                    };
                    variantViewModels.Add(variantViewModel);
                }

                var questionViewModel = new QuestionViewModel
                {
                    Ask = question.Ask,
                    Answer = question.Answer,
                    VariantViewModels = variantViewModels,
                };
                questionViewModels.Add(questionViewModel);
            }

            var quizViewModel = new QuizViewModel
            {
                Id = quiz.Id,
                Title = quiz.Title,
                QuestionViewModels = questionViewModels,
            };

            return View(quizViewModel);
        }

        public IActionResult DeleteQuiz(int id)
        {
            var quiz = _quizRepository.GetById(id);
            _quizRepository.Delete(quiz);

            return RedirectToAction("myQuizzes");
        }
    }
}

TestProjectWeb/Views/Quiz/CreateQuiz.cshtml
@model CreateQuizViewModel

<div class="parent-for-all-fields">
    <div class="fields">
        <div class="fields-title">
            Create Quiz
        </div>
        <form method="post" asp-controller="Quiz" asp-action="CreateQuiz" asp-antiforgery="true">
            <div>
                <div>
                    <label asp-for="Title"></label>
                </div>
                <div>
                    <input type="text" asp-for="Title" />
                </div>
            </div>
            <div>
                <div>
                    <label asp-for="QuestionsQuantity"></label>
                    <span asp-validation-for="QuestionsQuantity"></span>
                </div>
                <div>
                    <input type="number" asp-for="QuestionsQuantity" />
                </div>
            </div>
            <div>
                <input type="submit" value="Create" />
            </div>
        </form>
    </div>
</div>

TestProjectWeb/Views/Quiz/PlayQuiz.cshtml
@model QuizViewModel
@section Scripts{
<script src="~/js/quiz.js"></script>
}

<div class="quiz-content">
    <div>
        Quiz id: @Model.Id
    </div>
    <div>
        Quiz Title: @Model.Title
    </div>
    <div>
        @{int index = 0;}
        @foreach (var questionViewModel in @Model.QuestionViewModels)
        {
            <div>
                <div class="quiz-ask-@index">
                    Ask: @questionViewModel.Ask
                </div>
                Your answer:
                <select class="quiz-userAnswer-@index" name="answer">
                    @foreach (var variantViewModel in questionViewModel.VariantViewModels)
                    {

                        <option value="@variantViewModel.Value">
                            @variantViewModel.Value
                        </option>
                    }
                </select>
                <input type="hidden" class="quiz-correctAnswer-@index" value="@questionViewModel.Answer"></input>
            </div>
            index++;
        }
    </div>
    <div>
        <input class="check-quiz" type="submit" value="Check" />
        <a asp-controller="Quiz" asp-action="MyQuizzes">Back</a>
    </div>
</div>

TestProjectWeb/Views/Quiz/myQuizzes.cshtml
@model List<QuizViewModel>

<div class="quiz-content">
    <div>
        My Quizzes!!!
    </div>
    <div class="myQuizzes-quiz-table">
        <div class="myQuizzes-quiz-table-columns table-row">
            <div class="table-column-title">
                <div>
                    Id
                </div>
            </div>
            <div class="table-column-title">
                <div>
                    Title
                </div>
            </div>
        </div>
        <div>
            @foreach (var quiz in Model)
            {
                <div class="myQuizzes-quiz-table-columns table-row">
                    <div class="table-column-item">
                        <div>
                            <span>
                                @quiz.Id
                            </span>
                            <span>
                                <a asp-controller="Quiz" asp-action="PlayQuiz" asp-route-id="@quiz.Id">Play</a>
                                <a asp-controller="Quiz" asp-action="DeleteQuiz" asp-route-id="@quiz.Id">Delete</a>
                            </span>
                        </div>
                    </div>
                    <div class="table-column-item">
                        <div>
                            @quiz.Title
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <div>
        <a asp-controller="Quiz" asp-action="CreateQuiz">Create quiz</a>
    </div>
</div>