TestProjectWeb/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace TestProjectWeb.Models
{
    public class LoginViewModel
    {
        [Required]
        public string Login { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

TestProjectWeb/Models/ProfileViewModel.cs
namespace TestProjectWeb.Models
{
    public class ProfileViewModel
    {
        public UserViewModel UserViewModel { get; set; }
        public List<WordViewModel> WordViewModels { get; set; }
    }
}

TestProjectWeb/Models/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;
using TestProjectWeb.Data.Enums;

namespace TestProjectWeb.Models
{
    public class RegisterViewModel
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public string Country { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        public string LearningLanguage { get; set; }
        [Required]
        public LanguageLevel LanguageLevel { get; set; }

        [Required]
        public string Login { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

TestProjectWeb/Models/UserViewModel.cs
using TestProjectWeb.Data.Enums;

namespace TestProjectWeb.Models
{
    public class UserViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string LearningLanguage { get; set; }
        public LanguageLevel LanguageLevel { get; set; }
    }
}

TestProjectWeb/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TestProjectWeb.Data;
using TestProjectWeb.Data.DbModels;
using TestProjectWeb.Models;
using TestProjectWeb.Services;

namespace TestProjectWeb.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private WordRepository _wordRepository;
        private UserRepository _userRepository;
        private UserService _userService;

        public ProfileController(ApplicationDbContext dbContext,
                              UserRepository userRepository,
                              UserService userService, 
                              WordRepository wordRepository)
        {
            _userRepository = userRepository;
            _userService = userService;
            _wordRepository = wordRepository;
        }
        
        [HttpGet]
        public IActionResult Profile(string seacrhWord)
        {
            var profileViewModel = new ProfileViewModel();

            var user = _userService.GetCurrentUser();
            var userViewModel = new UserViewModel
            {
                Id = user.Id,
                Name = user.Name,
                Country = user.Country,
                City = user.City,
                LearningLanguage = user.LearningLanguage,
                LanguageLevel = user.LanguageLevel,
            };


            var wordViewModels = new List<WordViewModel>();

            var words = new List<Word>();
            if (seacrhWord == "" || seacrhWord == null)
            {
                words = _wordRepository.GetAllByCreaterId(user.Id);
            }
            else
            {
                words = _wordRepository.GetAllByCreaterId(user.Id)
                    .Where(x => x.Value.Contains(seacrhWord) ||
                                x.Translation.Contains(seacrhWord) ||
                                x.Category.Contains(seacrhWord)).ToList();
            }

            foreach (var word in words)
            {
                var wordViewModel = new WordViewModel();
                wordViewModel.Id = word.Id;
                wordViewModel.Value = word.Value;
                wordViewModel.Translation = word.Translation;
                wordViewModel.Category = word.Category;
                wordViewModel.PartOfSpeech = word.PartOfSpeech;

                wordViewModels.Add(wordViewModel);
            }

            profileViewModel.UserViewModel = userViewModel;
            profileViewModel.WordViewModels = wordViewModels;
            
            return View(profileViewModel);
        }

        [HttpPost]
        public IActionResult EditProfile(ProfileViewModel profileViewModel)
        {
            var user = _userService.GetCurrentUser();
            user.Name = profileViewModel.UserViewModel.Name;

            _userRepository.Edit(user);

            return RedirectToAction("Profile");
        }
    }
}

TestProjectWeb/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TestProjectWeb.Data;
using TestProjectWeb.Models;
using TestProjectWeb.Services;

namespace TestProjectWeb.Controllers
{
    public class UserController : Controller
    {
        private UserRepository _userRepository;
        private UserService _userService;
        private WordRepository _wordRepository;

        public UserController(UserRepository userRepository, WordRepository wordRepository, UserService userService)
        {
            _userRepository = userRepository;
            _wordRepository = wordRepository;
            _userService = userService;
        }

        public IActionResult AllUsers()
        {
            var users = _userRepository.GetAll();
            var usersViewModels = new List<UserViewModel>();
            foreach (var user in users)
            {
                var userViewModel = new UserViewModel 
                { 
                    Id = user.Id,
                    Name = user.Name,
                    Country = user.Country,
                    City = user.City,
                    LearningLanguage = user.LearningLanguage,
                    LanguageLevel = user.LanguageLevel,
                };
                usersViewModels.Add(userViewModel);
            }
            return View(usersViewModels);
        }

        public IActionResult UserProfile(int id)
        {
            if (id == _userService.GetCurrentUser()?.Id)
            {
                return RedirectToAction("Profile", "Profile");
            }

            var profileViewModel = new ProfileViewModel();
            var userViewModel = new UserViewModel();
            var wordViewModels = new List<WordViewModel>();

            var user = _userRepository.GetById(id);
            if (user == null)
            {
                return RedirectToAction("AllUsers");
            }
            userViewModel.Id = user.Id;
            userViewModel.Name = user.Name;
            userViewModel.Country = user.Country;
            userViewModel.City = user.City;
            userViewModel.LearningLanguage = user.LearningLanguage;
            userViewModel.LanguageLevel = user.LanguageLevel;


            var words = _wordRepository.GetAllByCreaterId(id);
            foreach (var word in words)
            {
                var wordViewModel = new WordViewModel();
                wordViewModel.Id = word.Id;
                wordViewModel.Value = word.Value;
                wordViewModel.Translation = word.Translation;
                wordViewModel.Category = word.Category;
                wordViewModel.PartOfSpeech = word.PartOfSpeech;
                wordViewModel.CreaterId = word.Creater.Id;

                wordViewModels.Add(wordViewModel);
            }

            profileViewModel.UserViewModel = userViewModel;
            profileViewModel.WordViewModels = wordViewModels;
            return View(profileViewModel);
        }
    }
}

TestProjectWeb/Controllers/WordController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TestProjectWeb.Data;
using TestProjectWeb.Data.DbModels;
using TestProjectWeb.Data.Enums;
using TestProjectWeb.Models;
using TestProjectWeb.Services;

namespace TestProjectWeb.Controllers
{
    [Authorize]
    public class WordController : Controller
    {
        private WordRepository _wordRepository;
        private UserService _userService;

        public WordController(WordRepository wordRepository,
                              UserService userService)
        {
            _wordRepository = wordRepository;
            _userService = userService;
        }

        [HttpGet]
        public IActionResult CreateWord()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateWord(WordViewModel wordViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var user = _userService.GetCurrentUser();

            var word = new Word();
            word.Value = wordViewModel.Value.ToLower();
            word.Translation = wordViewModel.Translation.ToLower();
            word.Category = wordViewModel.Category.ToLower();
            word.PartOfSpeech = wordViewModel.PartOfSpeech;
            word.Creater = user;

            _wordRepository.Create(word);
            return RedirectToAction("Profile", "Profile");
        }

        [HttpGet]
        public IActionResult EditWord(int id)
        {
            var word = _wordRepository.GetById(id);

            var wordViewModel = new WordViewModel();
            wordViewModel.Value = word.Value;
            wordViewModel.Translation = word.Translation;
            wordViewModel.Category = word.Category;
            wordViewModel.PartOfSpeech = word.PartOfSpeech;


            return View(wordViewModel);
        }
        [HttpPost]
        public IActionResult EditWord(WordViewModel wordViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var user = _userService.GetCurrentUser();

            var word = new Word();
            word.Id = wordViewModel.Id;
            word.Value = wordViewModel.Value.ToLower();
            word.Translation = wordViewModel.Translation.ToLower();
            word.Category = wordViewModel.Category.ToLower();
            word.PartOfSpeech = wordViewModel.PartOfSpeech;
            word.Creater = user;

            _wordRepository.Edit(word);

            return RedirectToAction("Profile", "Profile");
        }

        public IActionResult DeleteWord(int id)
        {
            var word = _wordRepository.GetById(id);
            _wordRepository.Delete(word);

            return RedirectToAction("Profile", "Profile");
        }

        public IActionResult CopyWord(int createrId, string value, string translation, string category, PartsOfSpeech partOfSpeech)
        {
            var user = _userService.GetCurrentUser();

            var word = new Word();
            word.Value = value;
            word.Translation = translation;
            word.Category = category;
            word.PartOfSpeech = partOfSpeech;
            word.Creater = user;

            _wordRepository.Create(word);

            return RedirectToAction("UserProfile", "User", new {@id = createrId});
        }
    }
}

TestProjectWeb/Views/User/AllUsers.cshtml
@using TestProjectWeb.Models
@model List<UserViewModel>

<div class="allUsers">
    <div class="allUsers-users-table">
        <div class="allUsers-users-table-columns table-row">
            <div class="table-column-title">
                <div>
                    Id
                </div>
            </div>
            <div class="table-column-title">
                <div>
                    Name
                </div>
            </div>
            <div class="table-column-title">
                <div>
                    Country
                </div>
            </div>
            <div class="table-column-title">
                <div>
                    City
                </div>
            </div>
            <div class="table-column-title">
                <div>
                    LearningLanguage
                </div>
            </div>
            <div class="table-column-title">
                <div>
                    LanguageLevel
                </div>
            </div>
        </div>
        @foreach (var user in Model)
        {
            <div class="allUsers-users-table-columns table-row">
                <div class="table-column-item">
                    <div>
                        @user.Id
                    </div>
                </div>
                <div class="table-column-item">
                    <div>
                        <a asp-controller="User" asp-action="UserProfile" asp-route-id="@user.Id">@user.Name</a>                        
                    </div>
                </div>
                <div class="table-column-item">
                    <div>
                        @user.Country
                    </div>
                </div>
                <div class="table-column-item">
                    <div>
                        @user.City
                    </div>
                </div>
                <div class="table-column-item">
                    <div>
                        @user.LearningLanguage
                    </div>
                </div>
                <div class="table-column-item">
                    <div>
                        @user.LanguageLevel
                    </div>
                </div>
            </div>
        }
    </div>
</div>

TestProjectWeb/Views/User/Index.cshtml
@using TestProjectWeb.Models
@model List<UserViewModel>

<div class="user-index-container">
    <div class="user-index-title">
        All users:
    </div>
    <div class="user-index-list">          
        @foreach (var user in Model)
        {
            <div class="user-index-list-item"> 
                <span class="user-index-list-item-name"> User: @user.Name </span>
                <a class="user-index-list-item-link" asp-area="" asp-controller="User" asp-action="DeleteUser" asp-route-id="@user.Id">Delete</a>
            </div>
        }   
    </div>  
</div>

TestProjectWeb/Views/User/Login.cshtml
@model LoginViewModel

<div class="login">
    Login
     <form method="post" asp-controller="User" asp-action="Login" asp-antiforgery="true">
        <div>
            <label asp-for="Name"></label>
            <input type="text" asp-for="Name" />
        </div>
        <div>
            <label asp-for="Password"></label>
            <input type="text" asp-for="Password" />
        </div>

        <div>
            <input type="submit" value="Login" />
        </div>
     </form>
     <a asp-area="" asp-controller="User" asp-action="Register">Register</a>
     <a asp-area="" asp-controller="Home" asp-action="Index">Back</a>
</div>

TestProjectWeb/Views/User/Profile.cshtml
@using TestProjectWeb.Models;
@model ProfileViewModel

<div>
    Your profile:
    <div>
         Id: @Model.UserViewModel.Id
    </div>
    <div>
        Name: @Model.UserViewModel.Name
    </div>
    <div>
        Password: @Model.UserViewModel.Password
    </div>    
</div>

<div>
    @foreach (var word in @Model.WordViewModels)
    {
        <div>
            <span>Value: @word.Value     Translation: @word.Translation</span>
        </div>        
    }
</div>

<div>
    <a asp-area="" asp-controller="Word" asp-action="CreateWord">CreateWord</a>
</div>

<div>
    <a asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
</div>

TestProjectWeb/Views/User/Register.cshtml
@model RegisterViewModel

<div class="Register">
    Register
     <form method="post" asp-controller="User" asp-action="Register" asp-antiforgery="true">
        <div>
            <label asp-for="Name"></label>
            <input type="text" asp-for="Name" />
        </div>
        <div>
            <label asp-for="Password"></label>
            <input type="text" asp-for="Password" />
        </div>

        <div>
            <input type="submit" value="Register" />
        </div>
     </form>
     <a asp-area="" asp-controller="Home" asp-action="Index">Back</a>
</div>

TestProjectWeb/Views/User/UserProfile.cshtml
@using TestProjectWeb.Models;
@model ProfileViewModel

<div class="profile">
    <div class="profile-side">
        <div class="profile-side-info">
            <div>
                Profile info:
            </div>
            <div>
                Id: @Model.UserViewModel.Id
            </div>
            <div>
                Name: @Model.UserViewModel.Name
            </div>
            <div>
                Country: @Model.UserViewModel.Country
            </div>
            <div>
                City: @Model.UserViewModel.City
            </div>
            <div>
                LearningLanguage: @Model.UserViewModel.LearningLanguage
            </div>
            <div>
                LanguageLevel: @Model.UserViewModel.LanguageLevel
            </div>
        </div>
    </div>
    <div class="profile-content">
        <div class="user-word-table">
            <div class="user-word-table-columns table-row">
                <div class="table-column-title">
                    <div>
                        Word
                    </div>
                </div>
                <div class="table-column-title">
                    <div>
                        Translation
                    </div>
                </div>
                <div class="table-column-title">
                    <div>
                        Category
                    </div>
                </div>
                <div class="table-column-title">
                    <div>
                        Part of Speech
                    </div>
                </div>
            </div>
            @foreach (var word in @Model.WordViewModels)
            {
                <div class="user-word-table-columns table-row">
                    <div class="table-column-item">
                        <div>
                            <span>
                                @word.Value
                            </span>
                            <span>
                                @{
                                    var parms = new Dictionary<string, string>
                                        {
                                            { "createrId", @word.CreaterId.ToString() },
                                            { "value", @word.Value },
                                            {"translation", @word.Translation },
                                            {"category", @word.Category },
                                            {"partOfSpeech", @word.PartOfSpeech.ToString() }
                                        };
                                }
                                <a asp-controller="Word" asp-action="CopyWord" asp-all-route-data="parms">C</a>
                            </span>
                        </div>
                    </div>
                    <div class="table-column-item">
                        <div>
                            @word.Translation
                        </div>
                    </div>
                    <div class="table-column-item">
                        <div>
                            @word.Category
                        </div>
                    </div>
                    <div class="table-column-item">
                        <div>
                            @word.PartOfSpeech
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>